#############################################################################
# Makefile for building: mam
# Generated by qmake (2.01a) (Qt 4.7.3) on: Wed May 25 04:34:51 2011
# Project:  ../mam/mam.pro
# Template: subdirs
# Command: /usr/bin/qmake -spec /usr/lib/qt4/mkspecs/linux-g++ -o Makefile ../mam/mam.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-components \
		sub-backend \
		sub-frontend

components/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) components/ || $(MKDIR) components/ 
	cd components/ && $(QMAKE) /home/paulo_data/Mandriva/Projects/mam/components/components.pro -spec /usr/lib/qt4/mkspecs/linux-g++ -o $(MAKEFILE)
sub-components-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) components/ || $(MKDIR) components/ 
	cd components/ && $(QMAKE) /home/paulo_data/Mandriva/Projects/mam/components/components.pro -spec /usr/lib/qt4/mkspecs/linux-g++ -o $(MAKEFILE)
sub-components: components/$(MAKEFILE) FORCE
	cd components/ && $(MAKE) -f $(MAKEFILE)
sub-components-make_default: components/$(MAKEFILE) FORCE
	cd components/ && $(MAKE) -f $(MAKEFILE) 
sub-components-make_first: components/$(MAKEFILE) FORCE
	cd components/ && $(MAKE) -f $(MAKEFILE) first
sub-components-all: components/$(MAKEFILE) FORCE
	cd components/ && $(MAKE) -f $(MAKEFILE) all
sub-components-clean: components/$(MAKEFILE) FORCE
	cd components/ && $(MAKE) -f $(MAKEFILE) clean
sub-components-distclean: components/$(MAKEFILE) FORCE
	cd components/ && $(MAKE) -f $(MAKEFILE) distclean
sub-components-install_subtargets: components/$(MAKEFILE) FORCE
	cd components/ && $(MAKE) -f $(MAKEFILE) install
sub-components-uninstall_subtargets: components/$(MAKEFILE) FORCE
	cd components/ && $(MAKE) -f $(MAKEFILE) uninstall
backend/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) backend/ || $(MKDIR) backend/ 
	cd backend/ && $(QMAKE) /home/paulo_data/Mandriva/Projects/mam/backend/backend.pro -spec /usr/lib/qt4/mkspecs/linux-g++ -o $(MAKEFILE)
sub-backend-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) backend/ || $(MKDIR) backend/ 
	cd backend/ && $(QMAKE) /home/paulo_data/Mandriva/Projects/mam/backend/backend.pro -spec /usr/lib/qt4/mkspecs/linux-g++ -o $(MAKEFILE)
sub-backend: backend/$(MAKEFILE) FORCE
	cd backend/ && $(MAKE) -f $(MAKEFILE)
sub-backend-make_default: backend/$(MAKEFILE) FORCE
	cd backend/ && $(MAKE) -f $(MAKEFILE) 
sub-backend-make_first: backend/$(MAKEFILE) FORCE
	cd backend/ && $(MAKE) -f $(MAKEFILE) first
sub-backend-all: backend/$(MAKEFILE) FORCE
	cd backend/ && $(MAKE) -f $(MAKEFILE) all
sub-backend-clean: backend/$(MAKEFILE) FORCE
	cd backend/ && $(MAKE) -f $(MAKEFILE) clean
sub-backend-distclean: backend/$(MAKEFILE) FORCE
	cd backend/ && $(MAKE) -f $(MAKEFILE) distclean
sub-backend-install_subtargets: backend/$(MAKEFILE) FORCE
	cd backend/ && $(MAKE) -f $(MAKEFILE) install
sub-backend-uninstall_subtargets: backend/$(MAKEFILE) FORCE
	cd backend/ && $(MAKE) -f $(MAKEFILE) uninstall
frontend/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) frontend/ || $(MKDIR) frontend/ 
	cd frontend/ && $(QMAKE) /home/paulo_data/Mandriva/Projects/mam/frontend/frontend.pro -spec /usr/lib/qt4/mkspecs/linux-g++ -o $(MAKEFILE)
sub-frontend-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) frontend/ || $(MKDIR) frontend/ 
	cd frontend/ && $(QMAKE) /home/paulo_data/Mandriva/Projects/mam/frontend/frontend.pro -spec /usr/lib/qt4/mkspecs/linux-g++ -o $(MAKEFILE)
sub-frontend: frontend/$(MAKEFILE) FORCE
	cd frontend/ && $(MAKE) -f $(MAKEFILE)
sub-frontend-make_default: frontend/$(MAKEFILE) FORCE
	cd frontend/ && $(MAKE) -f $(MAKEFILE) 
sub-frontend-make_first: frontend/$(MAKEFILE) FORCE
	cd frontend/ && $(MAKE) -f $(MAKEFILE) first
sub-frontend-all: frontend/$(MAKEFILE) FORCE
	cd frontend/ && $(MAKE) -f $(MAKEFILE) all
sub-frontend-clean: frontend/$(MAKEFILE) FORCE
	cd frontend/ && $(MAKE) -f $(MAKEFILE) clean
sub-frontend-distclean: frontend/$(MAKEFILE) FORCE
	cd frontend/ && $(MAKE) -f $(MAKEFILE) distclean
sub-frontend-install_subtargets: frontend/$(MAKEFILE) FORCE
	cd frontend/ && $(MAKE) -f $(MAKEFILE) install
sub-frontend-uninstall_subtargets: frontend/$(MAKEFILE) FORCE
	cd frontend/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: ../mam/mam.pro  /usr/lib/qt4/mkspecs/linux-g++/qmake.conf /usr/lib/qt4/mkspecs/common/g++.conf \
		/usr/lib/qt4/mkspecs/common/unix.conf \
		/usr/lib/qt4/mkspecs/common/linux.conf \
		/usr/lib/qt4/mkspecs/qconfig.pri \
		/usr/lib/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/lib/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/lib/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib/qt4/mkspecs/features/qt_config.prf \
		/usr/lib/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt4/mkspecs/features/default_pre.prf \
		/usr/lib/qt4/mkspecs/features/release.prf \
		/usr/lib/qt4/mkspecs/features/default_post.prf \
		/usr/lib/qt4/mkspecs/features/warn_on.prf \
		/usr/lib/qt4/mkspecs/features/qt.prf \
		/usr/lib/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib/qt4/mkspecs/features/moc.prf \
		/usr/lib/qt4/mkspecs/features/resources.prf \
		/usr/lib/qt4/mkspecs/features/uic.prf \
		/usr/lib/qt4/mkspecs/features/yacc.prf \
		/usr/lib/qt4/mkspecs/features/lex.prf \
		/usr/lib/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /usr/lib/qt4/mkspecs/linux-g++ -o Makefile ../mam/mam.pro
/usr/lib/qt4/mkspecs/common/g++.conf:
/usr/lib/qt4/mkspecs/common/unix.conf:
/usr/lib/qt4/mkspecs/common/linux.conf:
/usr/lib/qt4/mkspecs/qconfig.pri:
/usr/lib/qt4/mkspecs/modules/qt_phonon.pri:
/usr/lib/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/lib/qt4/mkspecs/features/qt_functions.prf:
/usr/lib/qt4/mkspecs/features/qt_config.prf:
/usr/lib/qt4/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt4/mkspecs/features/default_pre.prf:
/usr/lib/qt4/mkspecs/features/release.prf:
/usr/lib/qt4/mkspecs/features/default_post.prf:
/usr/lib/qt4/mkspecs/features/warn_on.prf:
/usr/lib/qt4/mkspecs/features/qt.prf:
/usr/lib/qt4/mkspecs/features/unix/thread.prf:
/usr/lib/qt4/mkspecs/features/moc.prf:
/usr/lib/qt4/mkspecs/features/resources.prf:
/usr/lib/qt4/mkspecs/features/uic.prf:
/usr/lib/qt4/mkspecs/features/yacc.prf:
/usr/lib/qt4/mkspecs/features/lex.prf:
/usr/lib/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -spec /usr/lib/qt4/mkspecs/linux-g++ -o Makefile ../mam/mam.pro

qmake_all: sub-components-qmake_all sub-backend-qmake_all sub-frontend-qmake_all FORCE

make_default: sub-components-make_default sub-backend-make_default sub-frontend-make_default FORCE
make_first: sub-components-make_first sub-backend-make_first sub-frontend-make_first FORCE
all: sub-components-all sub-backend-all sub-frontend-all FORCE
clean: sub-components-clean sub-backend-clean sub-frontend-clean FORCE
distclean: sub-components-distclean sub-backend-distclean sub-frontend-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-components-install_subtargets sub-backend-install_subtargets sub-frontend-install_subtargets FORCE
uninstall_subtargets: sub-components-uninstall_subtargets sub-backend-uninstall_subtargets sub-frontend-uninstall_subtargets FORCE

sub-components-check: components/$(MAKEFILE)
	cd components/ && $(MAKE) check
sub-backend-check: backend/$(MAKEFILE)
	cd backend/ && $(MAKE) check
sub-frontend-check: frontend/$(MAKEFILE)
	cd frontend/ && $(MAKE) check
check: sub-components-check sub-backend-check sub-frontend-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

